name: CI

on:
  pull_request:
    types: [opened, edited]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t ddb

    - name: Run CMake tests
      run: docker run ddb
