name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the DDB Docker image
      run: docker build . --file Dockerfile -t ddb:$(date +%s) --target test
